# Automatic Wi-Fi reconnection
CONFIG_ESP32_WIFI_STA_RECONNECT=y

# ESP32-C3 DevKitC has limited flash - use minimal coredump format
CONFIG_DEBUG_COREDUMP_MEMORY_DUMP_MIN=y

# Reduce coredump memory footprint to fit within the smaller partition
CONFIG_HEAP_MEM_POOL_ADD_SIZE_SPOTFLOW_COREDUMPS=8192
CONFIG_SPOTFLOW_COREDUMPS_CHUNK_SIZE=1024
CONFIG_SPOTFLOW_COREDUMPS_BACKEND_QUEUE_SIZE=7
